// Generated by supabase/postgres-meta from the applied migrations (schema: public).
// Regenerate with: npm run gen:types   (see docs/DB-TYPES.md). Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      approved_goal: {
        Row: {
          anchor_minus1: string | null
          anchor_minus2: string | null
          anchor_plus1: string | null
          anchor_plus2: string | null
          anchor_zero: string | null
          approved_at: string
          approved_by_clinician_id: string
          baseline_video_path: string | null
          goal_kind: Database["public"]["Enums"]["goal_kind"]
          goal_outcome: Database["public"]["Enums"]["goal_outcome"] | null
          id: string
          lineage_id: string
          nrs_baseline_value: number | null
          nrs_cut_high: number | null
          nrs_cut_low: number | null
          nrs_cut_low_low: number | null
          nrs_cut_zero: number | null
          nrs_direction: Database["public"]["Enums"]["nrs_direction"] | null
          nrs_question: string | null
          nrs_target_value: number | null
          patient_facing_text: string
          patient_id: string
          smart_text: string
          status: Database["public"]["Enums"]["approved_goal_status"]
          suggestion_id: string | null
          superseded_at: string | null
          superseded_by: string | null
          therapy: string
          treatment_cycle_id: string
          version: number
          video_enabled: boolean
          video_task_instruction: string | null
          video_task_seconds: number | null
          video_task_setup: string | null
        }
        Insert: {
          anchor_minus1?: string | null
          anchor_minus2?: string | null
          anchor_plus1?: string | null
          anchor_plus2?: string | null
          anchor_zero?: string | null
          approved_at?: string
          approved_by_clinician_id: string
          baseline_video_path?: string | null
          goal_kind?: Database["public"]["Enums"]["goal_kind"]
          goal_outcome?: Database["public"]["Enums"]["goal_outcome"] | null
          id?: string
          lineage_id: string
          nrs_baseline_value?: number | null
          nrs_cut_high?: number | null
          nrs_cut_low?: number | null
          nrs_cut_low_low?: number | null
          nrs_cut_zero?: number | null
          nrs_direction?: Database["public"]["Enums"]["nrs_direction"] | null
          nrs_question?: string | null
          nrs_target_value?: number | null
          patient_facing_text: string
          patient_id: string
          smart_text: string
          status?: Database["public"]["Enums"]["approved_goal_status"]
          suggestion_id?: string | null
          superseded_at?: string | null
          superseded_by?: string | null
          therapy?: string
          treatment_cycle_id: string
          version?: number
          video_enabled?: boolean
          video_task_instruction?: string | null
          video_task_seconds?: number | null
          video_task_setup?: string | null
        }
        Update: {
          anchor_minus1?: string | null
          anchor_minus2?: string | null
          anchor_plus1?: string | null
          anchor_plus2?: string | null
          anchor_zero?: string | null
          approved_at?: string
          approved_by_clinician_id?: string
          baseline_video_path?: string | null
          goal_kind?: Database["public"]["Enums"]["goal_kind"]
          goal_outcome?: Database["public"]["Enums"]["goal_outcome"] | null
          id?: string
          lineage_id?: string
          nrs_baseline_value?: number | null
          nrs_cut_high?: number | null
          nrs_cut_low?: number | null
          nrs_cut_low_low?: number | null
          nrs_cut_zero?: number | null
          nrs_direction?: Database["public"]["Enums"]["nrs_direction"] | null
          nrs_question?: string | null
          nrs_target_value?: number | null
          patient_facing_text?: string
          patient_id?: string
          smart_text?: string
          status?: Database["public"]["Enums"]["approved_goal_status"]
          suggestion_id?: string | null
          superseded_at?: string | null
          superseded_by?: string | null
          therapy?: string
          treatment_cycle_id?: string
          version?: number
          video_enabled?: boolean
          video_task_instruction?: string | null
          video_task_seconds?: number | null
          video_task_setup?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "approved_goal_approved_by_clinician_id_fkey"
            columns: ["approved_by_clinician_id"]
            isOneToOne: false
            referencedRelation: "clinician"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "approved_goal_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "approved_goal_suggestion_id_fkey"
            columns: ["suggestion_id"]
            isOneToOne: true
            referencedRelation: "goal_suggestion"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "approved_goal_superseded_by_fkey"
            columns: ["superseded_by"]
            isOneToOne: false
            referencedRelation: "approved_goal"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "approved_goal_treatment_cycle_id_fkey"
            columns: ["treatment_cycle_id"]
            isOneToOne: false
            referencedRelation: "treatment_cycle"
            referencedColumns: ["id"]
          },
        ]
      }
      archived_goal_video: {
        Row: {
          approved_goal_id: string
          archived_at: string
          archived_by: string | null
          clinic_video_rating: number | null
          clinic_video_unusable: boolean
          consent_clinical: boolean
          consent_educational: boolean
          id: string
          note: string | null
          nrs_value: number | null
          patient_id: string
          rating_id: string | null
          source: string
          video_path: string
        }
        Insert: {
          approved_goal_id: string
          archived_at?: string
          archived_by?: string | null
          clinic_video_rating?: number | null
          clinic_video_unusable?: boolean
          consent_clinical?: boolean
          consent_educational?: boolean
          id?: string
          note?: string | null
          nrs_value?: number | null
          patient_id: string
          rating_id?: string | null
          source: string
          video_path: string
        }
        Update: {
          approved_goal_id?: string
          archived_at?: string
          archived_by?: string | null
          clinic_video_rating?: number | null
          clinic_video_unusable?: boolean
          consent_clinical?: boolean
          consent_educational?: boolean
          id?: string
          note?: string | null
          nrs_value?: number | null
          patient_id?: string
          rating_id?: string | null
          source?: string
          video_path?: string
        }
        Relationships: [
          {
            foreignKeyName: "archived_goal_video_approved_goal_id_fkey"
            columns: ["approved_goal_id"]
            isOneToOne: false
            referencedRelation: "approved_goal"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "archived_goal_video_archived_by_fkey"
            columns: ["archived_by"]
            isOneToOne: false
            referencedRelation: "profile"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "archived_goal_video_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "archived_goal_video_rating_id_fkey"
            columns: ["rating_id"]
            isOneToOne: false
            referencedRelation: "weekly_goal_rating"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_event: {
        Row: {
          action: string
          actor_profile_id: string | null
          actor_role: Database["public"]["Enums"]["role"]
          entity: string
          entity_id: string
          id: string
          metadata: Json | null
          occurred_at: string
        }
        Insert: {
          action: string
          actor_profile_id?: string | null
          actor_role: Database["public"]["Enums"]["role"]
          entity: string
          entity_id: string
          id?: string
          metadata?: Json | null
          occurred_at?: string
        }
        Update: {
          action?: string
          actor_profile_id?: string | null
          actor_role?: Database["public"]["Enums"]["role"]
          entity?: string
          entity_id?: string
          id?: string
          metadata?: Json | null
          occurred_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_event_actor_profile_id_fkey"
            columns: ["actor_profile_id"]
            isOneToOne: false
            referencedRelation: "profile"
            referencedColumns: ["id"]
          },
        ]
      }
      clinician: {
        Row: {
          created_at: string
          id: string
          profile_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          profile_id: string
        }
        Update: {
          created_at?: string
          id?: string
          profile_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "clinician_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "profile"
            referencedColumns: ["id"]
          },
        ]
      }
      clinician_session: {
        Row: {
          clinician_id: string
          end_reason: string | null
          ended_at: string | null
          id: string
          last_activity_at: string
          patient_id: string
          started_at: string
          visit_code: string
        }
        Insert: {
          clinician_id: string
          end_reason?: string | null
          ended_at?: string | null
          id?: string
          last_activity_at?: string
          patient_id: string
          started_at?: string
          visit_code: string
        }
        Update: {
          clinician_id?: string
          end_reason?: string | null
          ended_at?: string | null
          id?: string
          last_activity_at?: string
          patient_id?: string
          started_at?: string
          visit_code?: string
        }
        Relationships: [
          {
            foreignKeyName: "clinician_session_clinician_id_fkey"
            columns: ["clinician_id"]
            isOneToOne: false
            referencedRelation: "clinician"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "clinician_session_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "clinician_session_visit_code_fkey"
            columns: ["visit_code"]
            isOneToOne: false
            referencedRelation: "visit_code"
            referencedColumns: ["code"]
          },
        ]
      }
      device_push_token: {
        Row: {
          created_at: string
          id: string
          last_seen_at: string
          locale: string
          platform: string
          profile_id: string
          token: string
        }
        Insert: {
          created_at?: string
          id?: string
          last_seen_at?: string
          locale?: string
          platform: string
          profile_id: string
          token: string
        }
        Update: {
          created_at?: string
          id?: string
          last_seen_at?: string
          locale?: string
          platform?: string
          profile_id?: string
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "device_push_token_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profile"
            referencedColumns: ["id"]
          },
        ]
      }
      goal_handoff_note: {
        Row: {
          approved_goal_id: string
          created_at: string
          created_by: string | null
          id: string
          note: string
          patient_id: string
          treatment_cycle_id: string
          updated_at: string
        }
        Insert: {
          approved_goal_id: string
          created_at?: string
          created_by?: string | null
          id?: string
          note: string
          patient_id: string
          treatment_cycle_id: string
          updated_at?: string
        }
        Update: {
          approved_goal_id?: string
          created_at?: string
          created_by?: string | null
          id?: string
          note?: string
          patient_id?: string
          treatment_cycle_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "goal_handoff_note_approved_goal_id_fkey"
            columns: ["approved_goal_id"]
            isOneToOne: false
            referencedRelation: "approved_goal"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goal_handoff_note_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "clinician"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goal_handoff_note_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goal_handoff_note_treatment_cycle_id_fkey"
            columns: ["treatment_cycle_id"]
            isOneToOne: false
            referencedRelation: "treatment_cycle"
            referencedColumns: ["id"]
          },
        ]
      }
      goal_suggestion: {
        Row: {
          combined_into_goal_id: string | null
          created_at: string
          difficulty_context: string | null
          domain: Database["public"]["Enums"]["goal_domain"]
          hoped_timeframe: Database["public"]["Enums"]["hoped_timeframe"]
          id: string
          importance: Database["public"]["Enums"]["importance"]
          patient_id: string
          patient_wording: string
          status: Database["public"]["Enums"]["suggestion_status"]
          submitter_label: Database["public"]["Enums"]["submitter_label"]
          treatment_cycle_id: string | null
        }
        Insert: {
          combined_into_goal_id?: string | null
          created_at?: string
          difficulty_context?: string | null
          domain: Database["public"]["Enums"]["goal_domain"]
          hoped_timeframe?: Database["public"]["Enums"]["hoped_timeframe"]
          id?: string
          importance: Database["public"]["Enums"]["importance"]
          patient_id: string
          patient_wording: string
          status?: Database["public"]["Enums"]["suggestion_status"]
          submitter_label?: Database["public"]["Enums"]["submitter_label"]
          treatment_cycle_id?: string | null
        }
        Update: {
          combined_into_goal_id?: string | null
          created_at?: string
          difficulty_context?: string | null
          domain?: Database["public"]["Enums"]["goal_domain"]
          hoped_timeframe?: Database["public"]["Enums"]["hoped_timeframe"]
          id?: string
          importance?: Database["public"]["Enums"]["importance"]
          patient_id?: string
          patient_wording?: string
          status?: Database["public"]["Enums"]["suggestion_status"]
          submitter_label?: Database["public"]["Enums"]["submitter_label"]
          treatment_cycle_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "goal_suggestion_combined_into_goal_id_fkey"
            columns: ["combined_into_goal_id"]
            isOneToOne: false
            referencedRelation: "approved_goal"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goal_suggestion_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goal_suggestion_treatment_cycle_id_fkey"
            columns: ["treatment_cycle_id"]
            isOneToOne: false
            referencedRelation: "treatment_cycle"
            referencedColumns: ["id"]
          },
        ]
      }
      itb_dose_change: {
        Row: {
          changed_on: string
          created_at: string
          created_by: string | null
          dose_mcg_per_day: number | null
          id: string
          itb_therapy_id: string
          note: string | null
        }
        Insert: {
          changed_on: string
          created_at?: string
          created_by?: string | null
          dose_mcg_per_day?: number | null
          id?: string
          itb_therapy_id: string
          note?: string | null
        }
        Update: {
          changed_on?: string
          created_at?: string
          created_by?: string | null
          dose_mcg_per_day?: number | null
          id?: string
          itb_therapy_id?: string
          note?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "itb_dose_change_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "clinician"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "itb_dose_change_itb_therapy_id_fkey"
            columns: ["itb_therapy_id"]
            isOneToOne: false
            referencedRelation: "itb_therapy"
            referencedColumns: ["id"]
          },
        ]
      }
      itb_therapy: {
        Row: {
          created_at: string
          created_by: string | null
          ended_on: string | null
          id: string
          note: string | null
          patient_id: string
          started_on: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          ended_on?: string | null
          id?: string
          note?: string | null
          patient_id: string
          started_on?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          ended_on?: string | null
          id?: string
          note?: string | null
          patient_id?: string
          started_on?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "itb_therapy_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "clinician"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "itb_therapy_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
        ]
      }
      muscle_injection: {
        Row: {
          dose_units: number
          id: string
          muscle: string
          note: string | null
          pos_x: number | null
          pos_y: number | null
          position: number
          side: Database["public"]["Enums"]["injection_side"]
          treatment_session_id: string
        }
        Insert: {
          dose_units: number
          id?: string
          muscle: string
          note?: string | null
          pos_x?: number | null
          pos_y?: number | null
          position?: number
          side: Database["public"]["Enums"]["injection_side"]
          treatment_session_id: string
        }
        Update: {
          dose_units?: number
          id?: string
          muscle?: string
          note?: string | null
          pos_x?: number | null
          pos_y?: number | null
          position?: number
          side?: Database["public"]["Enums"]["injection_side"]
          treatment_session_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "muscle_injection_treatment_session_id_fkey"
            columns: ["treatment_session_id"]
            isOneToOne: false
            referencedRelation: "treatment_session"
            referencedColumns: ["id"]
          },
        ]
      }
      observation: {
        Row: {
          code: string
          code_system: string
          created_at: string
          device_label: string | null
          display: string | null
          effective_end: string | null
          effective_time: string
          external_id: string
          id: string
          imported_by_clinician_id: string | null
          patient_id: string
          raw: Json | null
          source: Database["public"]["Enums"]["observation_source"]
          treatment_cycle_id: string | null
          unit: string | null
          value_numeric: number | null
          value_text: string | null
        }
        Insert: {
          code: string
          code_system?: string
          created_at?: string
          device_label?: string | null
          display?: string | null
          effective_end?: string | null
          effective_time: string
          external_id?: string
          id?: string
          imported_by_clinician_id?: string | null
          patient_id: string
          raw?: Json | null
          source: Database["public"]["Enums"]["observation_source"]
          treatment_cycle_id?: string | null
          unit?: string | null
          value_numeric?: number | null
          value_text?: string | null
        }
        Update: {
          code?: string
          code_system?: string
          created_at?: string
          device_label?: string | null
          display?: string | null
          effective_end?: string | null
          effective_time?: string
          external_id?: string
          id?: string
          imported_by_clinician_id?: string | null
          patient_id?: string
          raw?: Json | null
          source?: Database["public"]["Enums"]["observation_source"]
          treatment_cycle_id?: string | null
          unit?: string | null
          value_numeric?: number | null
          value_text?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "observation_imported_by_clinician_id_fkey"
            columns: ["imported_by_clinician_id"]
            isOneToOne: false
            referencedRelation: "clinician"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "observation_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "observation_treatment_cycle_id_fkey"
            columns: ["treatment_cycle_id"]
            isOneToOne: false
            referencedRelation: "treatment_cycle"
            referencedColumns: ["id"]
          },
        ]
      }
      patient: {
        Row: {
          affected_side: Database["public"]["Enums"]["injection_side"] | null
          ambulation: Database["public"]["Enums"]["ambulation_status"] | null
          background_notes: string | null
          birth_year: number | null
          created_at: string
          current_medication: string | null
          date_of_birth: string | null
          etiology: Database["public"]["Enums"]["etiology"] | null
          etiology_detail: string | null
          id: string
          onset_year: number | null
          physio_assistive_devices: string | null
          physio_exercise_plan: string | null
          previous_medication: string | null
          profile_id: string
          research_consent: boolean
          research_consent_purged_at: string | null
          research_consent_recorded_at: string | null
          research_consent_recorded_by: string | null
          research_consent_source: string | null
          research_consent_withdrawn_at: string | null
          sex: Database["public"]["Enums"]["patient_sex"] | null
          share_muscles_with_physio: boolean
          study_code: string | null
          video_consent_clinical: boolean
          video_consent_educational: boolean
          video_consent_recorded_at: string | null
          video_consent_recorded_by: string | null
          video_consent_source: string | null
          wearable_enabled: boolean
        }
        Insert: {
          affected_side?: Database["public"]["Enums"]["injection_side"] | null
          ambulation?: Database["public"]["Enums"]["ambulation_status"] | null
          background_notes?: string | null
          birth_year?: number | null
          created_at?: string
          current_medication?: string | null
          date_of_birth?: string | null
          etiology?: Database["public"]["Enums"]["etiology"] | null
          etiology_detail?: string | null
          id?: string
          onset_year?: number | null
          physio_assistive_devices?: string | null
          physio_exercise_plan?: string | null
          previous_medication?: string | null
          profile_id: string
          research_consent?: boolean
          research_consent_purged_at?: string | null
          research_consent_recorded_at?: string | null
          research_consent_recorded_by?: string | null
          research_consent_source?: string | null
          research_consent_withdrawn_at?: string | null
          sex?: Database["public"]["Enums"]["patient_sex"] | null
          share_muscles_with_physio?: boolean
          study_code?: string | null
          video_consent_clinical?: boolean
          video_consent_educational?: boolean
          video_consent_recorded_at?: string | null
          video_consent_recorded_by?: string | null
          video_consent_source?: string | null
          wearable_enabled?: boolean
        }
        Update: {
          affected_side?: Database["public"]["Enums"]["injection_side"] | null
          ambulation?: Database["public"]["Enums"]["ambulation_status"] | null
          background_notes?: string | null
          birth_year?: number | null
          created_at?: string
          current_medication?: string | null
          date_of_birth?: string | null
          etiology?: Database["public"]["Enums"]["etiology"] | null
          etiology_detail?: string | null
          id?: string
          onset_year?: number | null
          physio_assistive_devices?: string | null
          physio_exercise_plan?: string | null
          previous_medication?: string | null
          profile_id?: string
          research_consent?: boolean
          research_consent_purged_at?: string | null
          research_consent_recorded_at?: string | null
          research_consent_recorded_by?: string | null
          research_consent_source?: string | null
          research_consent_withdrawn_at?: string | null
          sex?: Database["public"]["Enums"]["patient_sex"] | null
          share_muscles_with_physio?: boolean
          study_code?: string | null
          video_consent_clinical?: boolean
          video_consent_educational?: boolean
          video_consent_recorded_at?: string | null
          video_consent_recorded_by?: string | null
          video_consent_source?: string | null
          wearable_enabled?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "patient_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "profile"
            referencedColumns: ["id"]
          },
        ]
      }
      physio_assessment: {
        Row: {
          assessment_date: string
          created_at: string
          id: string
          note: string | null
          patient_id: string
          physiotherapist_id: string
          treatment_cycle_id: string
        }
        Insert: {
          assessment_date: string
          created_at?: string
          id?: string
          note?: string | null
          patient_id: string
          physiotherapist_id: string
          treatment_cycle_id: string
        }
        Update: {
          assessment_date?: string
          created_at?: string
          id?: string
          note?: string | null
          patient_id?: string
          physiotherapist_id?: string
          treatment_cycle_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "physio_assessment_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "physio_assessment_physiotherapist_id_fkey"
            columns: ["physiotherapist_id"]
            isOneToOne: false
            referencedRelation: "clinician"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "physio_assessment_treatment_cycle_id_fkey"
            columns: ["treatment_cycle_id"]
            isOneToOne: false
            referencedRelation: "treatment_cycle"
            referencedColumns: ["id"]
          },
        ]
      }
      physio_goal_rating: {
        Row: {
          adjustment_note: string | null
          adjustment_resolved_at: string | null
          adjustment_resolved_by: string | null
          adjustment_status: string
          approved_goal_id: string
          gas_value: number | null
          id: string
          needs_adjustment: boolean
          nrs_value: number | null
          physio_assessment_id: string
          working_on: boolean
        }
        Insert: {
          adjustment_note?: string | null
          adjustment_resolved_at?: string | null
          adjustment_resolved_by?: string | null
          adjustment_status?: string
          approved_goal_id: string
          gas_value?: number | null
          id?: string
          needs_adjustment?: boolean
          nrs_value?: number | null
          physio_assessment_id: string
          working_on?: boolean
        }
        Update: {
          adjustment_note?: string | null
          adjustment_resolved_at?: string | null
          adjustment_resolved_by?: string | null
          adjustment_status?: string
          approved_goal_id?: string
          gas_value?: number | null
          id?: string
          needs_adjustment?: boolean
          nrs_value?: number | null
          physio_assessment_id?: string
          working_on?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "physio_goal_rating_approved_goal_id_fkey"
            columns: ["approved_goal_id"]
            isOneToOne: false
            referencedRelation: "approved_goal"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "physio_goal_rating_physio_assessment_id_fkey"
            columns: ["physio_assessment_id"]
            isOneToOne: false
            referencedRelation: "physio_assessment"
            referencedColumns: ["id"]
          },
        ]
      }
      physio_goal_suggestion: {
        Row: {
          created_at: string
          id: string
          patient_id: string
          physiotherapist_id: string
          rationale: string
          status: Database["public"]["Enums"]["physio_review_status"]
          suggested_goal: string
          treatment_cycle_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          patient_id: string
          physiotherapist_id: string
          rationale: string
          status?: Database["public"]["Enums"]["physio_review_status"]
          suggested_goal: string
          treatment_cycle_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          patient_id?: string
          physiotherapist_id?: string
          rationale?: string
          status?: Database["public"]["Enums"]["physio_review_status"]
          suggested_goal?: string
          treatment_cycle_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "physio_goal_suggestion_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "physio_goal_suggestion_physiotherapist_id_fkey"
            columns: ["physiotherapist_id"]
            isOneToOne: false
            referencedRelation: "clinician"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "physio_goal_suggestion_treatment_cycle_id_fkey"
            columns: ["treatment_cycle_id"]
            isOneToOne: false
            referencedRelation: "treatment_cycle"
            referencedColumns: ["id"]
          },
        ]
      }
      physio_muscle_suggestion: {
        Row: {
          created_at: string
          id: string
          muscle: string
          patient_id: string
          physiotherapist_id: string
          rationale: string
          related_goal_id: string | null
          side: Database["public"]["Enums"]["injection_side"]
          status: Database["public"]["Enums"]["physio_review_status"]
          treatment_cycle_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          muscle: string
          patient_id: string
          physiotherapist_id: string
          rationale: string
          related_goal_id?: string | null
          side: Database["public"]["Enums"]["injection_side"]
          status?: Database["public"]["Enums"]["physio_review_status"]
          treatment_cycle_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          muscle?: string
          patient_id?: string
          physiotherapist_id?: string
          rationale?: string
          related_goal_id?: string | null
          side?: Database["public"]["Enums"]["injection_side"]
          status?: Database["public"]["Enums"]["physio_review_status"]
          treatment_cycle_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "physio_muscle_suggestion_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "physio_muscle_suggestion_physiotherapist_id_fkey"
            columns: ["physiotherapist_id"]
            isOneToOne: false
            referencedRelation: "clinician"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "physio_muscle_suggestion_related_goal_id_fkey"
            columns: ["related_goal_id"]
            isOneToOne: false
            referencedRelation: "approved_goal"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "physio_muscle_suggestion_treatment_cycle_id_fkey"
            columns: ["treatment_cycle_id"]
            isOneToOne: false
            referencedRelation: "treatment_cycle"
            referencedColumns: ["id"]
          },
        ]
      }
      profile: {
        Row: {
          color_scheme: string | null
          created_at: string
          deactivated_at: string | null
          display_name: string
          email: string | null
          has_seen_intro: boolean
          id: string
          is_admin: boolean
          layout_preference: string
          must_change_password: boolean
          nav_style: string
          night_mode: boolean
          notify_weekday: number | null
          preferred_locale: string
          profession: string | null
          profession_other: string | null
          read_aloud: boolean
          role: Database["public"]["Enums"]["role"]
          text_scale: number
        }
        Insert: {
          color_scheme?: string | null
          created_at?: string
          deactivated_at?: string | null
          display_name: string
          email?: string | null
          has_seen_intro?: boolean
          id: string
          is_admin?: boolean
          layout_preference?: string
          must_change_password?: boolean
          nav_style?: string
          night_mode?: boolean
          notify_weekday?: number | null
          preferred_locale?: string
          profession?: string | null
          profession_other?: string | null
          read_aloud?: boolean
          role: Database["public"]["Enums"]["role"]
          text_scale?: number
        }
        Update: {
          color_scheme?: string | null
          created_at?: string
          deactivated_at?: string | null
          display_name?: string
          email?: string | null
          has_seen_intro?: boolean
          id?: string
          is_admin?: boolean
          layout_preference?: string
          must_change_password?: boolean
          nav_style?: string
          night_mode?: boolean
          notify_weekday?: number | null
          preferred_locale?: string
          profession?: string | null
          profession_other?: string | null
          read_aloud?: boolean
          role?: Database["public"]["Enums"]["role"]
          text_scale?: number
        }
        Relationships: []
      }
      push_subscription: {
        Row: {
          auth: string
          created_at: string
          endpoint: string
          id: string
          last_seen_at: string
          locale: string
          p256dh: string
          profile_id: string
        }
        Insert: {
          auth: string
          created_at?: string
          endpoint: string
          id?: string
          last_seen_at?: string
          locale?: string
          p256dh: string
          profile_id: string
        }
        Update: {
          auth?: string
          created_at?: string
          endpoint?: string
          id?: string
          last_seen_at?: string
          locale?: string
          p256dh?: string
          profile_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_subscription_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profile"
            referencedColumns: ["id"]
          },
        ]
      }
      study: {
        Row: {
          active: boolean
          created_at: string
          created_by: string | null
          description: string | null
          id: string
          key: string
          name: string
          updated_at: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          key: string
          name: string
          updated_at?: string
        }
        Update: {
          active?: boolean
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          key?: string
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      study_membership: {
        Row: {
          enrolled_at: string
          enrolled_by: string | null
          id: string
          patient_id: string
          study_id: string
        }
        Insert: {
          enrolled_at?: string
          enrolled_by?: string | null
          id?: string
          patient_id: string
          study_id: string
        }
        Update: {
          enrolled_at?: string
          enrolled_by?: string | null
          id?: string
          patient_id?: string
          study_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "study_membership_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "study_membership_study_id_fkey"
            columns: ["study_id"]
            isOneToOne: false
            referencedRelation: "study"
            referencedColumns: ["id"]
          },
        ]
      }
      therapist_note: {
        Row: {
          body: string
          created_at: string
          id: string
          patient_id: string
          physiotherapist_id: string
          seen_at: string | null
          seen_by: string | null
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          patient_id: string
          physiotherapist_id: string
          seen_at?: string | null
          seen_by?: string | null
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          patient_id?: string
          physiotherapist_id?: string
          seen_at?: string | null
          seen_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "therapist_note_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "therapist_note_physiotherapist_id_fkey"
            columns: ["physiotherapist_id"]
            isOneToOne: false
            referencedRelation: "clinician"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "therapist_note_seen_by_fkey"
            columns: ["seen_by"]
            isOneToOne: false
            referencedRelation: "clinician"
            referencedColumns: ["id"]
          },
        ]
      }
      treatment_cycle: {
        Row: {
          clinician_note: string | null
          created_at: string
          cycle_number: number
          face_display_mode: Database["public"]["Enums"]["face_display_mode"]
          id: string
          includes_face: boolean
          includes_standard: boolean
          modality: Database["public"]["Enums"]["treatment_modality"]
          patient_id: string
          start_date: string
          status: Database["public"]["Enums"]["cycle_status"]
        }
        Insert: {
          clinician_note?: string | null
          created_at?: string
          cycle_number: number
          face_display_mode?: Database["public"]["Enums"]["face_display_mode"]
          id?: string
          includes_face?: boolean
          includes_standard?: boolean
          modality?: Database["public"]["Enums"]["treatment_modality"]
          patient_id: string
          start_date: string
          status?: Database["public"]["Enums"]["cycle_status"]
        }
        Update: {
          clinician_note?: string | null
          created_at?: string
          cycle_number?: number
          face_display_mode?: Database["public"]["Enums"]["face_display_mode"]
          id?: string
          includes_face?: boolean
          includes_standard?: boolean
          modality?: Database["public"]["Enums"]["treatment_modality"]
          patient_id?: string
          start_date?: string
          status?: Database["public"]["Enums"]["cycle_status"]
        }
        Relationships: [
          {
            foreignKeyName: "treatment_cycle_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
        ]
      }
      treatment_handoff: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          note: string | null
          patient_id: string
          treatment_changed: boolean | null
          treatment_cycle_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          note?: string | null
          patient_id: string
          treatment_changed?: boolean | null
          treatment_cycle_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          note?: string | null
          patient_id?: string
          treatment_changed?: boolean | null
          treatment_cycle_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "treatment_handoff_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "clinician"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "treatment_handoff_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "treatment_handoff_treatment_cycle_id_fkey"
            columns: ["treatment_cycle_id"]
            isOneToOne: true
            referencedRelation: "treatment_cycle"
            referencedColumns: ["id"]
          },
        ]
      }
      treatment_session: {
        Row: {
          date: string
          dilution: string | null
          drug_product: string
          guidance: Database["public"]["Enums"]["guidance_method"]
          id: string
          notes: string | null
          patient_id: string
          recorded_at: string
          recorded_by_clinician_id: string
          total_units: number
          treatment_cycle_id: string
        }
        Insert: {
          date: string
          dilution?: string | null
          drug_product: string
          guidance: Database["public"]["Enums"]["guidance_method"]
          id?: string
          notes?: string | null
          patient_id: string
          recorded_at?: string
          recorded_by_clinician_id: string
          total_units: number
          treatment_cycle_id: string
        }
        Update: {
          date?: string
          dilution?: string | null
          drug_product?: string
          guidance?: Database["public"]["Enums"]["guidance_method"]
          id?: string
          notes?: string | null
          patient_id?: string
          recorded_at?: string
          recorded_by_clinician_id?: string
          total_units?: number
          treatment_cycle_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "treatment_session_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "treatment_session_recorded_by_clinician_id_fkey"
            columns: ["recorded_by_clinician_id"]
            isOneToOne: false
            referencedRelation: "clinician"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "treatment_session_treatment_cycle_id_fkey"
            columns: ["treatment_cycle_id"]
            isOneToOne: true
            referencedRelation: "treatment_cycle"
            referencedColumns: ["id"]
          },
        ]
      }
      visit_code: {
        Row: {
          code: string
          consumed_at: string | null
          consumed_by_clinician_id: string | null
          created_at: string
          expires_at: string
          is_reusable: boolean
          patient_id: string
        }
        Insert: {
          code: string
          consumed_at?: string | null
          consumed_by_clinician_id?: string | null
          created_at?: string
          expires_at: string
          is_reusable?: boolean
          patient_id: string
        }
        Update: {
          code?: string
          consumed_at?: string | null
          consumed_by_clinician_id?: string | null
          created_at?: string
          expires_at?: string
          is_reusable?: boolean
          patient_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "visit_code_consumed_by_clinician_id_fkey"
            columns: ["consumed_by_clinician_id"]
            isOneToOne: false
            referencedRelation: "clinician"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "visit_code_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
        ]
      }
      visit_code_unlock_attempt: {
        Row: {
          attempted_at: string
          clinician_id: string
          id: string
          succeeded: boolean
        }
        Insert: {
          attempted_at?: string
          clinician_id: string
          id?: string
          succeeded: boolean
        }
        Update: {
          attempted_at?: string
          clinician_id?: string
          id?: string
          succeeded?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "visit_code_unlock_attempt_clinician_id_fkey"
            columns: ["clinician_id"]
            isOneToOne: false
            referencedRelation: "clinician"
            referencedColumns: ["id"]
          },
        ]
      }
      weekly_checkin: {
        Row: {
          comment: string | null
          daily_care: Database["public"]["Enums"]["daily_care"] | null
          id: string
          other_side_effect_text: string | null
          pain: number | null
          patient_id: string
          side_effects: Database["public"]["Enums"]["side_effect"][]
          spasm_frequency: Database["public"]["Enums"]["spasm_frequency"] | null
          stiffness: number | null
          submitted_at: string
          submitter_label: Database["public"]["Enums"]["submitter_label"]
          training_days: number[] | null
          training_days_therapist: number[] | null
          treatment_cycle_id: string
          week_number: number
          weekly_prompt_id: string
        }
        Insert: {
          comment?: string | null
          daily_care?: Database["public"]["Enums"]["daily_care"] | null
          id?: string
          other_side_effect_text?: string | null
          pain?: number | null
          patient_id: string
          side_effects?: Database["public"]["Enums"]["side_effect"][]
          spasm_frequency?:
            | Database["public"]["Enums"]["spasm_frequency"]
            | null
          stiffness?: number | null
          submitted_at?: string
          submitter_label?: Database["public"]["Enums"]["submitter_label"]
          training_days?: number[] | null
          training_days_therapist?: number[] | null
          treatment_cycle_id: string
          week_number: number
          weekly_prompt_id: string
        }
        Update: {
          comment?: string | null
          daily_care?: Database["public"]["Enums"]["daily_care"] | null
          id?: string
          other_side_effect_text?: string | null
          pain?: number | null
          patient_id?: string
          side_effects?: Database["public"]["Enums"]["side_effect"][]
          spasm_frequency?:
            | Database["public"]["Enums"]["spasm_frequency"]
            | null
          stiffness?: number | null
          submitted_at?: string
          submitter_label?: Database["public"]["Enums"]["submitter_label"]
          training_days?: number[] | null
          training_days_therapist?: number[] | null
          treatment_cycle_id?: string
          week_number?: number
          weekly_prompt_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "weekly_checkin_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "weekly_checkin_treatment_cycle_id_fkey"
            columns: ["treatment_cycle_id"]
            isOneToOne: false
            referencedRelation: "treatment_cycle"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "weekly_checkin_weekly_prompt_id_fkey"
            columns: ["weekly_prompt_id"]
            isOneToOne: true
            referencedRelation: "weekly_prompt"
            referencedColumns: ["id"]
          },
        ]
      }
      weekly_goal_rating: {
        Row: {
          approved_goal_id: string
          clinic_video_nrs: number | null
          clinic_video_rating: number | null
          clinic_video_scored_at: string | null
          clinic_video_scored_by: string | null
          clinic_video_unusable: boolean
          id: string
          nrs_value: number | null
          rating_label: Database["public"]["Enums"]["rating_label"] | null
          rating_value: number | null
          video_path: string | null
          weekly_checkin_id: string
        }
        Insert: {
          approved_goal_id: string
          clinic_video_nrs?: number | null
          clinic_video_rating?: number | null
          clinic_video_scored_at?: string | null
          clinic_video_scored_by?: string | null
          clinic_video_unusable?: boolean
          id?: string
          nrs_value?: number | null
          rating_label?: Database["public"]["Enums"]["rating_label"] | null
          rating_value?: number | null
          video_path?: string | null
          weekly_checkin_id: string
        }
        Update: {
          approved_goal_id?: string
          clinic_video_nrs?: number | null
          clinic_video_rating?: number | null
          clinic_video_scored_at?: string | null
          clinic_video_scored_by?: string | null
          clinic_video_unusable?: boolean
          id?: string
          nrs_value?: number | null
          rating_label?: Database["public"]["Enums"]["rating_label"] | null
          rating_value?: number | null
          video_path?: string | null
          weekly_checkin_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "weekly_goal_rating_approved_goal_id_fkey"
            columns: ["approved_goal_id"]
            isOneToOne: false
            referencedRelation: "approved_goal"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "weekly_goal_rating_clinic_video_scored_by_fkey"
            columns: ["clinic_video_scored_by"]
            isOneToOne: false
            referencedRelation: "clinician"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "weekly_goal_rating_weekly_checkin_id_fkey"
            columns: ["weekly_checkin_id"]
            isOneToOne: false
            referencedRelation: "weekly_checkin"
            referencedColumns: ["id"]
          },
        ]
      }
      weekly_prompt: {
        Row: {
          created_at: string
          due_date: string
          id: string
          notified_at: string | null
          patient_id: string
          reminded_at: string | null
          status: Database["public"]["Enums"]["prompt_status"]
          treatment_cycle_id: string
          week_number: number
        }
        Insert: {
          created_at?: string
          due_date: string
          id?: string
          notified_at?: string | null
          patient_id: string
          reminded_at?: string | null
          status?: Database["public"]["Enums"]["prompt_status"]
          treatment_cycle_id: string
          week_number: number
        }
        Update: {
          created_at?: string
          due_date?: string
          id?: string
          notified_at?: string | null
          patient_id?: string
          reminded_at?: string | null
          status?: Database["public"]["Enums"]["prompt_status"]
          treatment_cycle_id?: string
          week_number?: number
        }
        Relationships: [
          {
            foreignKeyName: "weekly_prompt_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "weekly_prompt_treatment_cycle_id_fkey"
            columns: ["treatment_cycle_id"]
            isOneToOne: false
            referencedRelation: "treatment_cycle"
            referencedColumns: ["id"]
          },
        ]
      }
      wearable_connection: {
        Row: {
          aggregator: string
          aggregator_user_id: string | null
          connected_at: string | null
          consented_at: string | null
          created_at: string
          id: string
          last_sync_at: string | null
          patient_id: string
          provider: string
          revoked_at: string | null
          status: Database["public"]["Enums"]["wearable_connection_status"]
        }
        Insert: {
          aggregator: string
          aggregator_user_id?: string | null
          connected_at?: string | null
          consented_at?: string | null
          created_at?: string
          id?: string
          last_sync_at?: string | null
          patient_id: string
          provider: string
          revoked_at?: string | null
          status?: Database["public"]["Enums"]["wearable_connection_status"]
        }
        Update: {
          aggregator?: string
          aggregator_user_id?: string | null
          connected_at?: string | null
          consented_at?: string | null
          created_at?: string
          id?: string
          last_sync_at?: string | null
          patient_id?: string
          provider?: string
          revoked_at?: string | null
          status?: Database["public"]["Enums"]["wearable_connection_status"]
        }
        Relationships: [
          {
            foreignKeyName: "wearable_connection_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patient"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      add_patient_to_study: {
        Args: { p_patient_id: string; p_study_id: string }
        Returns: undefined
      }
      approve_suggestion: {
        Args: {
          p_nrs_cut_high: number
          p_nrs_cut_low: number
          p_nrs_cut_low_low: number
          p_nrs_cut_zero: number
          p_nrs_direction: Database["public"]["Enums"]["nrs_direction"]
          p_nrs_question: string
          p_patient_facing_text: string
          p_smart_text: string
          p_suggestion_id: string
        }
        Returns: string
      }
      approve_suggestion_gas: {
        Args: {
          p_anchor_minus1: string
          p_anchor_minus2: string
          p_anchor_plus1: string
          p_anchor_plus2: string
          p_anchor_zero: string
          p_patient_facing_text: string
          p_smart_text: string
          p_suggestion_id: string
        }
        Returns: string
      }
      archive_goal: { Args: { p_goal_id: string }; Returns: undefined }
      archive_goal_video: {
        Args: {
          p_approved_goal_id: string
          p_note: string
          p_rating_id: string
          p_source: string
        }
        Returns: string
      }
      clear_goal_rating_video: {
        Args: { p_rating_id: string }
        Returns: undefined
      }
      clinician_can_access_patient: {
        Args: { p_patient_id: string }
        Returns: boolean
      }
      combine_suggestion_into_goal: {
        Args: { p_goal_id: string; p_suggestion_id: string }
        Returns: undefined
      }
      confirm_research_purge: {
        Args: { p_patient_id: string }
        Returns: undefined
      }
      create_gas_goal_for_patient: {
        Args: {
          p_anchor_minus1: string
          p_anchor_minus2: string
          p_anchor_plus1: string
          p_anchor_plus2: string
          p_anchor_zero: string
          p_patient_facing_text: string
          p_patient_id: string
          p_smart_text: string
        }
        Returns: string
      }
      create_goal_for_patient: {
        Args: {
          p_nrs_baseline_value: number
          p_nrs_cut_high: number
          p_nrs_cut_low: number
          p_nrs_cut_low_low: number
          p_nrs_cut_zero: number
          p_nrs_direction: Database["public"]["Enums"]["nrs_direction"]
          p_nrs_question: string
          p_nrs_target_value: number
          p_patient_facing_text: string
          p_patient_id: string
          p_smart_text: string
        }
        Returns: string
      }
      create_study: {
        Args: { p_description?: string; p_key: string; p_name: string }
        Returns: string
      }
      current_app_role: {
        Args: never
        Returns: Database["public"]["Enums"]["role"]
      }
      current_clinician_id: { Args: never; Returns: string }
      current_patient_id: { Args: never; Returns: string }
      current_profile_id: { Args: never; Returns: string }
      current_role_is_care_professional: { Args: never; Returns: boolean }
      current_user_is_admin: { Args: never; Returns: boolean }
      dearmor: { Args: { "": string }; Returns: string }
      dev_reseed_all: { Args: never; Returns: undefined }
      dev_seed_b1: { Args: never; Returns: undefined }
      dev_seed_b2: { Args: never; Returns: undefined }
      dev_seed_b3: { Args: never; Returns: undefined }
      dev_seed_b4: { Args: never; Returns: undefined }
      dev_seed_b5: { Args: never; Returns: undefined }
      dev_seed_b6: { Args: never; Returns: undefined }
      dev_seed_b7: { Args: never; Returns: undefined }
      dev_seed_b8: { Args: never; Returns: undefined }
      dev_seed_history_extras: { Args: never; Returns: undefined }
      edit_goal: {
        Args: {
          p_anchor_minus1?: string
          p_anchor_minus2?: string
          p_anchor_plus1?: string
          p_anchor_plus2?: string
          p_anchor_zero?: string
          p_nrs_baseline_value?: number
          p_nrs_cut_high?: number
          p_nrs_cut_low?: number
          p_nrs_cut_low_low?: number
          p_nrs_cut_zero?: number
          p_nrs_direction?: Database["public"]["Enums"]["nrs_direction"]
          p_nrs_question?: string
          p_nrs_target_value?: number
          p_patient_facing_text?: string
          p_smart_text?: string
          p_source_goal_id: string
        }
        Returns: string
      }
      end_clinician_session:
        | { Args: never; Returns: undefined }
        | { Args: { p_patient_id: string }; Returns: undefined }
      export_research_dataset: { Args: never; Returns: Json }
      gas_label: {
        Args: { p_gas: number }
        Returns: Database["public"]["Enums"]["rating_label"]
      }
      gen_random_uuid: { Args: never; Returns: string }
      gen_salt: { Args: { "": string }; Returns: string }
      generate_visit_code: {
        Args: { p_code: string }
        Returns: {
          code: string
          consumed_at: string | null
          consumed_by_clinician_id: string | null
          created_at: string
          expires_at: string
          is_reusable: boolean
          patient_id: string
        }
        SetofOptions: {
          from: "*"
          to: "visit_code"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      import_observations: {
        Args: { p_observations: Json; p_patient_id: string }
        Returns: number
      }
      link_goal_to_lineage: {
        Args: { p_source_goal_id: string; p_target_goal_id: string }
        Returns: string
      }
      list_my_sessions: {
        Args: never
        Returns: {
          display_name: string
          is_active: boolean
          last_activity_at: string
          patient_id: string
        }[]
      }
      log_itb_dose_change: {
        Args: {
          p_changed_on: string
          p_dose: number
          p_note: string
          p_therapy_id: string
        }
        Returns: undefined
      }
      mark_therapist_notes_seen: {
        Args: { p_patient_id: string }
        Returns: number
      }
      nrs_to_gas: {
        Args: {
          p_cut_high: number
          p_cut_low: number
          p_cut_low_low: number
          p_cut_zero: number
          p_direction: Database["public"]["Enums"]["nrs_direction"]
          p_nrs: number
        }
        Returns: number
      }
      pgp_armor_headers: {
        Args: { "": string }
        Returns: Record<string, unknown>[]
      }
      reactivate_goal: { Args: { p_goal_id: string }; Returns: undefined }
      register_device_push_token: {
        Args: { p_locale?: string; p_platform: string; p_token: string }
        Returns: undefined
      }
      remove_patient_from_study: {
        Args: { p_patient_id: string; p_study_id: string }
        Returns: undefined
      }
      reopen_session: { Args: { p_patient_id: string }; Returns: string }
      reopen_weekly_checkin: {
        Args: { p_checkin_id: string }
        Returns: undefined
      }
      resolve_adjustment_request: {
        Args: { p_rating_id: string; p_status: string }
        Returns: undefined
      }
      retire_goal: {
        Args: {
          p_goal_id: string
          p_outcome: Database["public"]["Enums"]["goal_outcome"]
        }
        Returns: undefined
      }
      save_treatment_session: {
        Args: {
          p_date: string
          p_dilution: string
          p_drug_product: string
          p_face_display_mode: Database["public"]["Enums"]["face_display_mode"]
          p_face_marks: Database["public"]["CompositeTypes"]["face_mark_input"][]
          p_guidance: Database["public"]["Enums"]["guidance_method"]
          p_includes_face: boolean
          p_includes_standard: boolean
          p_injections: Database["public"]["CompositeTypes"]["muscle_injection_input"][]
          p_notes: string
          p_total_units: number
          p_treatment_cycle_id: string
        }
        Returns: string
      }
      set_approved_goal_video_enabled: {
        Args: { p_enabled: boolean; p_goal_id: string }
        Returns: undefined
      }
      set_checkin_training_days: {
        Args: {
          p_checkin_id: string
          p_days: number[]
          p_days_therapist?: number[]
        }
        Returns: undefined
      }
      set_clinic_video_nrs: {
        Args: { p_nrs: number; p_rating_id: string; p_unusable: boolean }
        Returns: undefined
      }
      set_clinic_video_score: {
        Args: { p_rating: number; p_rating_id: string; p_unusable: boolean }
        Returns: undefined
      }
      set_cycle_clinician_note: {
        Args: { p_cycle_id: string; p_note: string }
        Returns: undefined
      }
      set_goal_baseline_video: {
        Args: { p_goal_id: string; p_path: string }
        Returns: undefined
      }
      set_goal_handoff_note: {
        Args: { p_cycle_id: string; p_goal_id: string; p_note: string }
        Returns: undefined
      }
      set_goal_therapy: {
        Args: { p_goal_id: string; p_therapy: string }
        Returns: undefined
      }
      set_goal_video_protocol: {
        Args: {
          p_goal_id: string
          p_instruction: string
          p_seconds: number
          p_setup: string
        }
        Returns: undefined
      }
      set_muscle_sharing: {
        Args: { p_patient_id: string; p_share: boolean }
        Returns: undefined
      }
      set_own_date_of_birth: {
        Args: { p_date_of_birth: string }
        Returns: undefined
      }
      set_own_research_consent: {
        Args: { p_consent: boolean }
        Returns: undefined
      }
      set_own_sex: {
        Args: { p_sex: Database["public"]["Enums"]["patient_sex"] }
        Returns: undefined
      }
      set_own_video_consent: {
        Args: { p_clinical: boolean; p_educational: boolean }
        Returns: undefined
      }
      set_patient_info: {
        Args: {
          p_affected_side: Database["public"]["Enums"]["injection_side"]
          p_ambulation: Database["public"]["Enums"]["ambulation_status"]
          p_assistive_devices: string
          p_background_notes: string
          p_date_of_birth: string
          p_etiology: Database["public"]["Enums"]["etiology"]
          p_etiology_detail: string
          p_onset_year: number
          p_patient_id: string
          p_sex: Database["public"]["Enums"]["patient_sex"]
        }
        Returns: undefined
      }
      set_patient_medication: {
        Args: {
          p_current_medication: string
          p_patient_id: string
          p_previous_medication: string
        }
        Returns: undefined
      }
      set_patient_research_consent: {
        Args: { p_consent: boolean; p_patient_id: string }
        Returns: undefined
      }
      set_patient_video_consent: {
        Args: {
          p_clinical: boolean
          p_educational: boolean
          p_patient_id: string
        }
        Returns: undefined
      }
      set_patient_wearable_enabled: {
        Args: { p_enabled: boolean; p_patient_id: string }
        Returns: undefined
      }
      set_physio_goal_suggestion_status: {
        Args: {
          p_status: Database["public"]["Enums"]["physio_review_status"]
          p_suggestion_id: string
        }
        Returns: undefined
      }
      set_physio_muscle_suggestion_status: {
        Args: {
          p_status: Database["public"]["Enums"]["physio_review_status"]
          p_suggestion_id: string
        }
        Returns: undefined
      }
      set_physio_plan: {
        Args: {
          p_assistive_devices: string
          p_exercise_plan: string
          p_patient_id: string
        }
        Returns: undefined
      }
      set_suggestion_status: {
        Args: {
          p_status: Database["public"]["Enums"]["suggestion_status"]
          p_suggestion_id: string
        }
        Returns: undefined
      }
      set_treatment_handoff: {
        Args: {
          p_cycle_id: string
          p_note: string
          p_treatment_changed: boolean
        }
        Returns: undefined
      }
      start_cycle_with_treatment: {
        Args: {
          p_dilution: string
          p_drug_product: string
          p_face_display_mode: Database["public"]["Enums"]["face_display_mode"]
          p_face_marks: Database["public"]["CompositeTypes"]["face_mark_input"][]
          p_guidance: Database["public"]["Enums"]["guidance_method"]
          p_includes_face: boolean
          p_includes_standard: boolean
          p_injections: Database["public"]["CompositeTypes"]["muscle_injection_input"][]
          p_notes: string
          p_patient_id: string
          p_total_units: number
          p_treatment_date: string
        }
        Returns: string
      }
      start_itb_therapy: {
        Args: { p_note: string; p_patient_id: string; p_started_on: string }
        Returns: string
      }
      start_new_cycle: {
        Args: { p_patient_id: string; p_treatment_date: string }
        Returns: string
      }
      study_overview: { Args: never; Returns: Json }
      submit_physio_assessment: {
        Args: {
          p_date: string
          p_note: string
          p_patient_id: string
          p_ratings: Database["public"]["CompositeTypes"]["physio_goal_rating_input_v3"][]
        }
        Returns: string
      }
      submit_physio_goal_suggestion: {
        Args: {
          p_patient_id: string
          p_rationale: string
          p_suggested_goal: string
        }
        Returns: string
      }
      submit_physio_muscle_suggestion: {
        Args: {
          p_muscle: string
          p_patient_id: string
          p_rationale: string
          p_related_goal_id?: string
          p_side: Database["public"]["Enums"]["injection_side"]
        }
        Returns: string
      }
      submit_therapist_note: {
        Args: { p_body: string; p_patient_id: string }
        Returns: string
      }
      submit_weekly_checkin: {
        Args: {
          p_comment?: string
          p_prompt_id: string
          p_ratings: Database["public"]["CompositeTypes"]["weekly_nrs_rating_input"][]
          p_submitter_label?: Database["public"]["Enums"]["submitter_label"]
        }
        Returns: string
      }
      submit_weekly_checkin_v3: {
        Args: {
          p_comment?: string
          p_prompt_id: string
          p_ratings: Database["public"]["CompositeTypes"]["weekly_goal_rating_input"][]
          p_submitter_label?: Database["public"]["Enums"]["submitter_label"]
        }
        Returns: string
      }
      submit_weekly_checkin_v4: {
        Args: {
          p_comment?: string
          p_prompt_id: string
          p_ratings: Database["public"]["CompositeTypes"]["weekly_goal_rating_input_v4"][]
          p_submitter_label?: Database["public"]["Enums"]["submitter_label"]
        }
        Returns: string
      }
      touch_clinician_session:
        | { Args: never; Returns: undefined }
        | { Args: { p_patient_id: string }; Returns: undefined }
      unarchive_goal_video: {
        Args: { p_archive_id: string }
        Returns: undefined
      }
      unlock_with_visit_code: { Args: { p_code: string }; Returns: string }
      update_study: {
        Args: {
          p_active?: boolean
          p_description?: string
          p_name?: string
          p_study_id: string
        }
        Returns: undefined
      }
      ingest_wearable_observations: {
        Args: {
          p_aggregator: string
          p_aggregator_user_id: string
          p_observations: Json
        }
        Returns: number
      }
      set_wearable_connection_status: {
        Args: {
          p_aggregator_user_id: string
          p_connection_id: string
          p_status: Database["public"]["Enums"]["wearable_connection_status"]
        }
        Returns: undefined
      }
    }
    Enums: {
      ambulation_status:
        | "independent"
        | "withAid"
        | "wheelchair"
        | "nonAmbulant"
      approved_goal_status: "active" | "archived" | "combined"
      cycle_status: "active" | "completed"
      daily_care:
        | "harder"
        | "unchanged"
        | "easier"
        | "muchEasier"
        | "notRelevant"
      etiology:
        | "stroke"
        | "tbi"
        | "cerebralPalsy"
        | "multipleSclerosis"
        | "spinalCordInjury"
        | "hereditarySpasticParaplegia"
        | "other"
        | "anoxic"
      face_display_mode: "color" | "symbol"
      goal_domain:
        | "pain"
        | "hygiene"
        | "dressing"
        | "walking"
        | "transfers"
        | "handUse"
        | "sleep"
        | "positioning"
        | "caregiverHelp"
        | "therapyExercise"
        | "other"
      goal_kind: "nrs" | "gas"
      goal_outcome: "achieved" | "partial" | "noLongerSuitable"
      guidance_method:
        | "emg"
        | "ultrasound"
        | "usEmg"
        | "electricalStimulation"
        | "anatomicalLandmarks"
        | "none"
        | "other"
      hoped_timeframe: "4w" | "8w" | "12w" | "notSure"
      importance: "low" | "medium" | "high"
      injection_side: "left" | "right" | "bilateral"
      nrs_direction: "higherIsBetter" | "lowerIsBetter"
      observation_source:
        | "manual"
        | "csv"
        | "apple_health"
        | "health_connect"
        | "garmin"
        | "fitbit"
        | "oura"
        | "withings"
        | "other"
      patient_sex: "female" | "male" | "other" | "preferNotToSay"
      physio_review_status:
        | "needsReview"
        | "accepted"
        | "reviewed"
        | "dismissed"
      prompt_status: "pending" | "completed"
      rating_label:
        | "muchWorseThanExpected"
        | "aLittleWorseThanExpected"
        | "asExpected"
        | "betterThanExpected"
        | "muchBetterThanExpected"
        | "notSure"
      role: "patient" | "clinician" | "admin" | "physiotherapist"
      side_effect: "weakness" | "falls" | "swallowing" | "fluLike" | "other"
      spasm_frequency: "none" | "occasional" | "daily" | "severalDaily"
      submitter_label: "self" | "caregiver"
      suggestion_status:
        | "needsReview"
        | "active"
        | "discussAtNextVisit"
        | "combinedWithAnother"
        | "notSuitableThisCycle"
        | "archived"
      treatment_modality:
        | "botulinum_toxin"
        | "baclofen_pump"
        | "surgery"
        | "other"
      wearable_connection_status:
        | "pending"
        | "connected"
        | "revoked"
        | "error"
    }
    CompositeTypes: {
      face_mark_input: {
        muscle: string | null
        side: Database["public"]["Enums"]["injection_side"] | null
        dose_units: number | null
        note: string | null
        pos_x: number | null
        pos_y: number | null
      }
      muscle_injection_input: {
        muscle: string | null
        side: Database["public"]["Enums"]["injection_side"] | null
        dose_units: number | null
        note: string | null
      }
      physio_goal_rating_input: {
        approved_goal_id: string | null
        nrs_value: number | null
      }
      physio_goal_rating_input_v2: {
        approved_goal_id: string | null
        nrs_value: number | null
        working_on: boolean | null
        needs_adjustment: boolean | null
        adjustment_note: string | null
      }
      physio_goal_rating_input_v3: {
        approved_goal_id: string | null
        nrs_value: number | null
        gas_value: number | null
        working_on: boolean | null
        needs_adjustment: boolean | null
        adjustment_note: string | null
      }
      weekly_goal_rating_input: {
        approved_goal_id: string | null
        nrs_value: number | null
        gas_value: number | null
      }
      weekly_goal_rating_input_v4: {
        approved_goal_id: string | null
        nrs_value: number | null
        gas_value: number | null
        video_path: string | null
      }
      weekly_nrs_rating_input: {
        approved_goal_id: string | null
        nrs_value: number | null
      }
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      ambulation_status: [
        "independent",
        "withAid",
        "wheelchair",
        "nonAmbulant",
      ],
      approved_goal_status: ["active", "archived", "combined"],
      cycle_status: ["active", "completed"],
      daily_care: [
        "harder",
        "unchanged",
        "easier",
        "muchEasier",
        "notRelevant",
      ],
      etiology: [
        "stroke",
        "tbi",
        "cerebralPalsy",
        "multipleSclerosis",
        "spinalCordInjury",
        "hereditarySpasticParaplegia",
        "other",
        "anoxic",
      ],
      face_display_mode: ["color", "symbol"],
      goal_domain: [
        "pain",
        "hygiene",
        "dressing",
        "walking",
        "transfers",
        "handUse",
        "sleep",
        "positioning",
        "caregiverHelp",
        "therapyExercise",
        "other",
      ],
      goal_kind: ["nrs", "gas"],
      goal_outcome: ["achieved", "partial", "noLongerSuitable"],
      guidance_method: [
        "emg",
        "ultrasound",
        "usEmg",
        "electricalStimulation",
        "anatomicalLandmarks",
        "none",
        "other",
      ],
      hoped_timeframe: ["4w", "8w", "12w", "notSure"],
      importance: ["low", "medium", "high"],
      injection_side: ["left", "right", "bilateral"],
      nrs_direction: ["higherIsBetter", "lowerIsBetter"],
      observation_source: [
        "manual",
        "csv",
        "apple_health",
        "health_connect",
        "garmin",
        "fitbit",
        "oura",
        "withings",
        "other",
      ],
      patient_sex: ["female", "male", "other", "preferNotToSay"],
      physio_review_status: [
        "needsReview",
        "accepted",
        "reviewed",
        "dismissed",
      ],
      prompt_status: ["pending", "completed"],
      rating_label: [
        "muchWorseThanExpected",
        "aLittleWorseThanExpected",
        "asExpected",
        "betterThanExpected",
        "muchBetterThanExpected",
        "notSure",
      ],
      role: ["patient", "clinician", "admin", "physiotherapist"],
      side_effect: ["weakness", "falls", "swallowing", "fluLike", "other"],
      spasm_frequency: ["none", "occasional", "daily", "severalDaily"],
      submitter_label: ["self", "caregiver"],
      suggestion_status: [
        "needsReview",
        "active",
        "discussAtNextVisit",
        "combinedWithAnother",
        "notSuitableThisCycle",
        "archived",
      ],
      treatment_modality: [
        "botulinum_toxin",
        "baclofen_pump",
        "surgery",
        "other",
      ],
      wearable_connection_status: [
        "pending",
        "connected",
        "revoked",
        "error",
      ],
    },
  },
} as const
