-- ============================================================================
-- 0022 — Add the physiotherapist role.
--
-- The care model has three professional-facing actors:
--   physician (role 'clinician')   — runs injection treatment, owns goals
--   physiotherapist (role 'physiotherapist') — running evaluations between
--                                    injection visits
--   admin (role 'admin')           — account management
--   plus the patient (role 'patient')
--
-- IMPORTANT naming note: the existing schema uses "clinician" for the
-- professional who unlocks a patient via a visit code. We are keeping
-- that name. From this migration on, "clinician" in table/function
-- names (clinician_session, current_clinician_id, the `clinician`
-- table) means "any unlocking professional" — physician OR
-- physiotherapist. The profile.role column is what distinguishes the
-- two. This avoids a disruptive rename across the codebase.
--
-- Concretely: a physiotherapist gets a row in the `clinician` table
-- (same as a physician) so they can be the subject of a
-- clinician_session. current_clinician_id() therefore works unchanged
-- for both. RLS that currently checks current_app_role() = 'clinician'
-- is updated where physiotherapists also need access.
-- ============================================================================

-- 1. Add the new enum value. Postgres allows adding enum values but
--    not in a transaction that also uses them, so this stands alone.
alter type role add value if not exists 'physiotherapist';
